### ISSUE TITLE
Auto - use "score" sequence from Teleop (driver right bumper)

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#111]
We have currently have 2 autos. 
-1st is the original that scores high and drives out of the community
2nd is the new one that scores then balances. This auto uses the new "score" sequence from the driver right bumper. 

Can we implement this in the first auto as well?

**Comment by MacPGamesAndApps** [comment]
@noahlinton, not too sure if it's implemented. I see all the autos doing their own custom sequences, but none is calling on the CmdGrpGamePieceScoring command group, which is what's being called from the driver right bumper.
It's possible though, that we just have a copy of the same commands as in CmdGrpGamePieceScoring, in the autos. Let's touch base and take a closer look together before I close this one.

**Comment by noahlinton** [comment]
@MacPGamesAndApps It's okay if it does not use the actual score command. The original issue was that our first auto did not drop and auto-retract. The auto's effectively do the correct thing. I would consider this a "clean up" task at this point, and the original intent of this issue is solved.

**Comment by MacPGamesAndApps** [comment]
Closing this one. We can create cleanup tasks later if needed- might be good coding practice too for off-season.
