### ISSUE TITLE
Addressable LED for game piece choice

### ISSUE THREAD

**Issue by BlakeMcFadden** [frc4039/2023#134]

**Comment by BlakeMcFadden** [comment]
Can reuse last years code: https://github.com/frc4039/2022/blob/main/2022/src/main/java/frc/robot/subsystems/AddressableLEDSubsystem.java

LED WPIlib library:  https://docs.wpilib.org/en/stable/docs/software/hardware-apis/misc/addressable-leds.html

**Comment by MacPGamesAndApps** [comment]
All done.
