### ISSUE TITLE
Update blue side auto's

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#152]
Need to create blue side auto for TwoPiecePurpleBarrier auto. Currently only RED logic and paths are correct.

**Comment by noahlinton** [comment]
Need to come up with a way to convert measurements of field during calibration, to points for the robot to follow. We should measure red side of practice field and see where we are.

**Comment by noahlinton** [comment]
Field has been checked by MattA. We can tune blue as needed

**Comment by MacPGamesAndApps** [comment]
All done.
