### ISSUE TITLE
Record current button mapping in Wiki page

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#23]
I believe @TravisMadill made a script in the past that automatically pulled the button mapping. Not sure if this is still in use.

**Comment by maisyt** [comment]
buttons are up to date

**Comment by Ben-Alderson** [comment]
Updated the Wiki pages for the controls:
[Driver](https://github.com/frc4039/2023/wiki/Driver-Gamepad-0) and [Operator](https://github.com/frc4039/2023/wiki/Operator-Gamepad-1)
