### ISSUE TITLE
Telescope - Add positions based on encoder

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#24]
As of Feb 6th, the belt on the telescope tends to skip, so positions may be hard to define. If the functionality can be added, then we can update the exact positions later.

**Comment by 4039-zach** [comment]
I already have the positions from Friday, but those may need to be updated eventually...

**Comment by 4039-zach** [comment]
May be fixed by [543bf808963383cd27e2b96cd8d73b4aa4429844](https://github.com/frc4039/2023/commit/543bf808963383cd27e2b96cd8d73b4aa4429844)

**Comment by 4039-zach** [comment]
Done!!!
