### ISSUE TITLE
Basic auto driving

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#25]
As always, we need a basic auto that moves forward, ideally with a delay timer. This is also a useful shakedown to ensure odometer is working.

**Comment by JacksonBarker** [comment]
aa7806b9061bd8d6c47711bd5fcaacf590aa8067

**Comment by JacksonBarker** [comment]
aa7806b9061bd8d6c47711bd5fcaacf590aa8067

**Comment by JacksonBarker** [comment]
Awaiting compressor for subsystem testing.

**Comment by noahlinton** [comment]
Can we pick this up as top priority? Ideally we would merge into DEV so that we can run a basic auto at the start of practice matches.
