### ISSUE TITLE
Investigate better control of pivot arm motion - See Mattward's comments in #controls

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#50]
Currently, the pivot arm's motion is jerky, and poorly tuned. There is high starting acceleration causing teeth on the chain to skip and lose position, as well as slow movement towards final position. Smart Motion on the spark max can be used for trapezoidal motion profiles, utilizing PID on velocity as well as position.

See example here: https://github.com/REVrobotics/SPARK-MAX-Examples/blob/master/Java/Smart%20Motion%20Example/src/main/java/frc/robot/Robot.java

**Comment by Redrield** [comment]
Note that I've heard smart motion can have some weird problems, as an alternative the motion profiling part can be done on the RIO, and used to produce position setpoints for the spark

https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/trapezoidal-profiles.html
