### ISSUE TITLE
Add Pneumatic Analog Pressure Reading to Smart Dashboard

### ISSUE THREAD

**Issue by Dairfey** [frc4039/2023#52]

**Comment by Ben-Alderson** [comment]
https://docs.wpilib.org/en/stable/docs/software/hardware-apis/pneumatics/pneumatics.html#pressure-transducers

**Comment by Ben-Alderson** [comment]
Need a pressure transducer to be added to the robot.

**Comment by Dairfey** [comment]
@Ben-Alderson should already be on the robot. May just need to be plugged in. @WyattDube can you confirm?

**Comment by Dairfey** [comment]
Talked to Wyatt. It is there, just needs to be plugged into the pneumatic hub.

**Comment by noahlinton** [comment]
@maisyt Can you look at doing this? Should be able to work on this remotely.
