### ISSUE TITLE
Remove the Intake extend from the cone pickup sequence

### ISSUE THREAD

**Issue by MacPGamesAndApps** [frc4039/2023#72]

**Comment by 4039-zach** [comment]
Fixed in/around [d5ca060](https://github.com/frc4039/2023/commit/d5ca0605040424736998596ce439115326ca3f70) (but now there's an IntakeRetract there that serves no purpose)

**Comment by MacPGamesAndApps** [comment]
It does serve a purpose- it's there in case the Operator goes directly from cube pickup to cone pickup. Also, I don't remember if it's been removed or not, but if not the Operator can manually extend the Intake, so in that case going to cone pickup needs the retract as well.
