### ISSUE TITLE
Automated scoring - see details

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#74]
This work is to optimize the scoring as much as possible. 

When approaching the scoring area on the field, operator can press a button to lower the pivot to the correct angle.
Then on button press, the arm extends. 
Final button press the gripper opens, and auto retracts to travel position. Can we move pivot and telescope at the same time, rather than sequentially?
Driver drives away. 

Update from Conversation:

Starting condition: Travel position
Operator A: Pivot angle to scoring angle
Operator Select Or Start: Extend to scoring location
Driver Right Bumper: SCORE! Lower pivot a little, open gripper, retract and pivot simultaneously to travel position
End condition: Travel position

**Comment by JacksonBarker** [comment]
d5ca0605040424736998596ce439115326ca3f70

**Comment by noahlinton** [comment]
@JacksonBarker how are things coming along here? Any progress today?

**Comment by JacksonBarker** [comment]
Has d5ca06 been tested?

**Comment by noahlinton** [comment]
We will review now and test. Can you give a summary of the changes? 

Side note: that commit has a TON of additions and deletions. Could that be caused by auto-formatting or something?

**Comment by JacksonBarker** [comment]
Yes, a large number of canges can be attributed to the new formatting consistency settings (see https://github.com/frc4039/2023/commit/b0be817bee4be4f51aec531f4a7f30a5a6d0ef8a).

The only user-facing changes are the buttons listed in the issue description.

**Comment by noahlinton** [comment]
Okay thanks! We are reviewing.

**Comment by noahlinton** [comment]
Comments from review:

Need to add safety to telescopic extend buttons - pivot must be at scoring angle to extend.

B (cone pickup) Calling two pivot commands in parallel - this is not good. Should only call cone pick up position.
X (cube pickup) sequentially went to scoring angle first, then cube pickup. Should not go to scoring angle first.
Right bumper Driver (SCORE!) works as intended!! Great!
Start & select buttons to extend work as intended except safety as mentioned above.

We can also remove the manual intake in and out buttons?
Also, can we move the intake spinning to right trigger on operator?

**Comment by JacksonBarker** [comment]
If you're still present feel free to try 90dea109d25b6a6cf9222d846e7f023f0960c36a. The intake trigger axis may need to be inverted so please tell me if the intake appears to be functionless. All other issues have been addressed 🤞

**Comment by noahlinton** [comment]
Done for the night. We can try tomorrow.

**Comment by noahlinton** [comment]
Can we close this? I think we have this solved. @JacksonBarker @MacPGamesAndApps
