### ISSUE TITLE
update cube pickup automations based on Feb 21st practice field learnings.

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#75]
This should be the intended flow.

Starting point: Travel Position
Operator X: Intake out, pivot arm stays in travel (or maybe moves down to a close location but NOT pickup location)
Operator Trigger: manual control of intake spinning
Operator bumpers: manual control of open/close gripper
Y Button: return to travel (arm up, intake in)

**Comment by noahlinton** [comment]
@MacPGamesAndApps This should take priority for tele-operated. We need to practice picking up cubes during matches

**Comment by MacPGamesAndApps** [comment]
All done and with some additional improvements.
