### ISSUE TITLE
Auto - Balance in Auto using Gyro

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2023#77]
Objective: Score "engaged" points by balancing on the charge station during auto. For this card, lets just focus on driving forward and balancing.

Lets try below as a starting point, then move from there:

Use PID to approach a gyro angle of 0 (NOT rate of change). 

I think the flow is as follows:
-Drive forward on the ground, looking for the ramp (angle will increase)
-Start driving slowly, looking for angle 0 on the gyro using PID? 
-When 0, stop driving.

**Comment by noahlinton** [comment]
@JacksonBarker Lets just do this as a starting point, and see how it goes. It could go horribly wrong, but I am interested

**Comment by noahlinton** [comment]
Whoops, closed by accident. Re-opened

**Comment by JacksonBarker** [comment]
Can test tomorrow
